apiVersion: v1
kind: Service
metadata:
  name: gogs
  namespace: vcs
  labels:
    app: gogs
    service: vcs
  annotations:
    'prometheus.io/scrape': 'true'
spec:
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: gogs
    service: vcs
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: gogs
  namespace: vcs
  labels:
    app: gogs
    service: vcs
spec:
  serviceName: gogs
  replicas: 1
  template:
    metadata:
      labels:
        app: gogs
        service: vcs
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: gogs
        image: gogs/gogs
        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 3000
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 1
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: "0.01"
        volumeMounts:
        - name: gogs-data
          mountPath: /data
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: gogs-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
